-- MySQL Script generated by MySQL Workbench
-- Wed Aug  8 08:05:43 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`facultad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`facultad` (
  `id_facultad` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_facultad` VARCHAR(30) NULL DEFAULT NULL,
  `direccion_facultad` VARCHAR(45) NULL DEFAULT NULL,
  `telefono_facultad` VARCHAR(15) NULL DEFAULT NULL,
  `correo_facultad` VARCHAR(35) NULL DEFAULT NULL,
  PRIMARY KEY (`id_facultad`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`carrera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`carrera` (
  `id_carrera` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_carrera` VARCHAR(30) NULL DEFAULT NULL,
  `FACULTAD_id_facultad` INT(11) NOT NULL,
  `jornada_carrera` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_carrera`),
  INDEX `fk_Carrera_Facultad_idx` (`FACULTAD_id_facultad` ASC),
  CONSTRAINT `fk_Carrera_Facultad`
    FOREIGN KEY (`FACULTAD_id_facultad`)
    REFERENCES `mydb`.`facultad` (`id_facultad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`alumno` (
  `dpi_alumno` INT(11) NOT NULL,
  `nombre_alumno` VARCHAR(30) NULL DEFAULT NULL,
  `apellido_alumno` VARCHAR(30) NULL DEFAULT NULL,
  `telefono_alumno` VARCHAR(15) NULL DEFAULT NULL,
  `correo_alumno` VARCHAR(35) NULL DEFAULT NULL,
  `FACULTAD_id_facultad` INT(11) NOT NULL,
  `CARRERA_id_carrera` INT(11) NOT NULL,
  `edad_alumno` INT(11) NULL DEFAULT NULL,
  `direccion_alumno` VARCHAR(45) NULL DEFAULT NULL,
  `estado_alumno` VARCHAR(45) NULL DEFAULT NULL,
  `carnet` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`dpi_alumno`),
  INDEX `fk_Alumno_Facultad1_idx` (`FACULTAD_id_facultad` ASC),
  INDEX `fk_Alumno_Carrera1_idx` (`CARRERA_id_carrera` ASC),
  CONSTRAINT `fk_Alumno_Carrera1`
    FOREIGN KEY (`CARRERA_id_carrera`)
    REFERENCES `mydb`.`carrera` (`id_carrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Alumno_Facultad1`
    FOREIGN KEY (`FACULTAD_id_facultad`)
    REFERENCES `mydb`.`facultad` (`id_facultad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`banco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`banco` (
  `id_banco` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_banco` VARCHAR(30) NULL DEFAULT NULL,
  `direccion_banco` VARCHAR(45) NULL DEFAULT NULL,
  `telefono_banco` VARCHAR(15) NULL DEFAULT NULL,
  PRIMARY KEY (`id_banco`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id_usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario_usuario` VARCHAR(45) NULL DEFAULT NULL,
  `nombre_usuario` VARCHAR(30) NULL DEFAULT NULL,
  `apellido_usuario` VARCHAR(30) NULL DEFAULT NULL,
  `password_usuario` VARCHAR(45) NULL DEFAULT NULL,
  `correo_usuario` VARCHAR(35) NULL DEFAULT NULL,
  `telefono_usuario` VARCHAR(15) NULL DEFAULT NULL,
  `nivel_privilegio` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `correo_usuario` (`correo_usuario` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`bitacora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bitacora` (
  `id_bitacora` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha_hora_bitacora` DATETIME NULL DEFAULT NULL,
  `accionusario_bitacora` VARCHAR(45) NULL DEFAULT NULL,
  `usuario_id_usuario` INT(11) NOT NULL,
  PRIMARY KEY (`id_bitacora`),
  INDEX `user_bitacora_idx` (`usuario_id_usuario` ASC),
  CONSTRAINT `user_bitacora`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 46
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`catedratico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`catedratico` (
  `dpi_catedratico` INT(11) NOT NULL,
  `nombre_catedratico` VARCHAR(30) NULL DEFAULT NULL,
  `apellido_catedratico` VARCHAR(30) NULL DEFAULT NULL,
  `telefono_catedratico` VARCHAR(15) NULL DEFAULT NULL,
  `correo_catedratico` VARCHAR(35) NULL DEFAULT NULL,
  `edad_catedratico` INT(11) NULL DEFAULT NULL,
  `direccion_catedratico` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`dpi_catedratico`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cuenta` (
  `id_cuenta` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_cuenta` VARCHAR(30) NULL DEFAULT NULL,
  `tipomoneda_cuenta` FLOAT NULL DEFAULT NULL,
  `tipo_cuenta` VARCHAR(45) NULL DEFAULT NULL,
  `saldo_cuenta` FLOAT NULL DEFAULT NULL,
  `BANCO_id_banco` INT(11) NOT NULL,
  PRIMARY KEY (`id_cuenta`),
  INDEX `fk_CUENTA_BANCO1_idx` (`BANCO_id_banco` ASC),
  CONSTRAINT `fk_CUENTA_BANCO1`
    FOREIGN KEY (`BANCO_id_banco`)
    REFERENCES `mydb`.`banco` (`id_banco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`pensum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pensum` (
  `id_pensum` INT(11) NOT NULL AUTO_INCREMENT,
  `CARRERA_id_carrera` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_pensum`),
  INDEX `fk_Pensum_Carrera1_idx` (`CARRERA_id_carrera` ASC),
  CONSTRAINT `fk_Pensum_Carrera1`
    FOREIGN KEY (`CARRERA_id_carrera`)
    REFERENCES `mydb`.`carrera` (`id_carrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`curso` (
  `id_curso` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_curso` VARCHAR(30) NULL DEFAULT NULL,
  `PENSUM_id_pensum` INT(11) NOT NULL,
  `semestre_curso` VARCHAR(45) NULL DEFAULT NULL,
  `creditos` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_curso`),
  INDEX `fk_Cursos_Pensum1_idx` (`PENSUM_id_pensum` ASC),
  CONSTRAINT `fk_Cursos_Pensum1`
    FOREIGN KEY (`PENSUM_id_pensum`)
    REFERENCES `mydb`.`pensum` (`id_pensum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`horario` (
  `id_horario` INT(11) NOT NULL AUTO_INCREMENT,
  `horario_horario` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_horario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`edificio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`edificio` (
  `id_edificio` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_edificio` VARCHAR(30) NULL DEFAULT NULL,
  `ubicacion_edificio` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_edificio`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`salon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`salon` (
  `id_salon` INT(11) NOT NULL AUTO_INCREMENT,
  `capacidad_salon` VARCHAR(45) NULL DEFAULT NULL,
  `EDIFICIO_id_edificio` INT(11) NOT NULL,
  `nombre_salon` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_salon`),
  INDEX `fk_Salones_Edificio1_idx` (`EDIFICIO_id_edificio` ASC),
  CONSTRAINT `fk_Salones_Edificio1`
    FOREIGN KEY (`EDIFICIO_id_edificio`)
    REFERENCES `mydb`.`edificio` (`id_edificio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`laboratorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`laboratorio` (
  `id_laboratorio` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion_laboratorio` VARCHAR(45) NULL DEFAULT NULL,
  `CATEDRATICO_dpi_catedratico` INT(11) NOT NULL,
  `HORARIO_id_horario` INT(11) NOT NULL,
  `SALON_id_salon` INT(11) NOT NULL,
  PRIMARY KEY (`id_laboratorio`),
  INDEX `fk_LABORATORIO_CATEDRATICO1_idx` (`CATEDRATICO_dpi_catedratico` ASC),
  INDEX `fk_LABORATORIO_HORARIO1_idx` (`HORARIO_id_horario` ASC),
  INDEX `fk_LABORATORIO_SALON1_idx` (`SALON_id_salon` ASC),
  CONSTRAINT `fk_LABORATORIO_CATEDRATICO1`
    FOREIGN KEY (`CATEDRATICO_dpi_catedratico`)
    REFERENCES `mydb`.`catedratico` (`dpi_catedratico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LABORATORIO_HORARIO1`
    FOREIGN KEY (`HORARIO_id_horario`)
    REFERENCES `mydb`.`horario` (`id_horario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LABORATORIO_SALON1`
    FOREIGN KEY (`SALON_id_salon`)
    REFERENCES `mydb`.`salon` (`id_salon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`seccion_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`seccion_curso` (
  `id_seccion` INT(11) NOT NULL AUTO_INCREMENT,
  `seccion_seccion` VARCHAR(45) NULL DEFAULT NULL,
  `estado_seccion` VARCHAR(45) NULL DEFAULT NULL,
  `catedratico_id` INT(11) NULL DEFAULT NULL,
  `curso_id` INT(11) NULL DEFAULT NULL,
  `laboratorio_id` INT(11) NULL DEFAULT NULL,
  `salon_id` INT(11) NULL DEFAULT NULL,
  `horario_id` INT(11) NULL DEFAULT NULL,
  `ciclo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_seccion`),
  INDEX `catedratico_id_idx` (`catedratico_id` ASC),
  INDEX `curso_id_idx` (`curso_id` ASC),
  INDEX `laboratorio_fk_idx` (`laboratorio_id` ASC),
  INDEX `salon_fk_idx` (`salon_id` ASC),
  INDEX `horario_fk_idx` (`horario_id` ASC),
  CONSTRAINT `catedratico_id`
    FOREIGN KEY (`catedratico_id`)
    REFERENCES `mydb`.`catedratico` (`dpi_catedratico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `curso_id`
    FOREIGN KEY (`curso_id`)
    REFERENCES `mydb`.`curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `horario_fk`
    FOREIGN KEY (`horario_id`)
    REFERENCES `mydb`.`horario` (`id_horario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `laboratorio_fk`
    FOREIGN KEY (`laboratorio_id`)
    REFERENCES `mydb`.`laboratorio` (`id_laboratorio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `salon_fk`
    FOREIGN KEY (`salon_id`)
    REFERENCES `mydb`.`salon` (`id_salon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`curso_estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`curso_estudiante` (
  `ALUMNO_dpi_alumno` INT(11) NOT NULL,
  `CURSO_id_curso` INT(11) NOT NULL,
  `estado_cursoestudiante` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ALUMNO_dpi_alumno`, `CURSO_id_curso`),
  INDEX `fk_Alumno_has_Curso_Alumno1_idx` (`ALUMNO_dpi_alumno` ASC),
  INDEX `fk_Alumno_has_Curso_Curso1_idx` (`CURSO_id_curso` ASC),
  CONSTRAINT `fk_Alumno_has_Curso_Alumno1`
    FOREIGN KEY (`ALUMNO_dpi_alumno`)
    REFERENCES `mydb`.`alumno` (`dpi_alumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Alumno_has_Curso_Curso1`
    FOREIGN KEY (`CURSO_id_curso`)
    REFERENCES `mydb`.`seccion_curso` (`id_seccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pago` (
  `id_pago` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo_pago` VARCHAR(45) NULL DEFAULT NULL,
  `CUENTA_id_cuenta` INT(11) NOT NULL,
  `ALUMNO_dpi_alumno` INT(11) NOT NULL,
  `monto_pago` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id_pago`),
  INDEX `fk_PAGO_CUENTA1_idx` (`CUENTA_id_cuenta` ASC),
  INDEX `fk_PAGO_ALUMNO1_idx` (`ALUMNO_dpi_alumno` ASC),
  CONSTRAINT `fk_PAGO_ALUMNO1`
    FOREIGN KEY (`ALUMNO_dpi_alumno`)
    REFERENCES `mydb`.`alumno` (`dpi_alumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PAGO_CUENTA1`
    FOREIGN KEY (`CUENTA_id_cuenta`)
    REFERENCES `mydb`.`cuenta` (`id_cuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`perfil` (
  `id_perfil` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_perfil` VARCHAR(30) NULL DEFAULT NULL,
  `descripcion_perfil` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_perfil`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`perfil_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`perfil_usuario` (
  `PERFIL_id_perfil` INT(11) NOT NULL,
  `USUARIO_id_usuario` INT(11) NOT NULL,
  PRIMARY KEY (`PERFIL_id_perfil`, `USUARIO_id_usuario`),
  INDEX `fk_perfil_has_Usuario_perfil1_idx` (`PERFIL_id_perfil` ASC),
  INDEX `usuario_rol_idx` (`USUARIO_id_usuario` ASC),
  CONSTRAINT `fk_perfil_has_Usuario_perfil1`
    FOREIGN KEY (`PERFIL_id_perfil`)
    REFERENCES `mydb`.`perfil` (`id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `usuario_rol`
    FOREIGN KEY (`USUARIO_id_usuario`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`prerequisito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`prerequisito` (
  `CURSO_id_curso_requisito` INT(11) NOT NULL,
  `CURSO_id_curso_prerequisito` INT(11) NOT NULL,
  `creditos` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`CURSO_id_curso_requisito`, `CURSO_id_curso_prerequisito`),
  INDEX `fk_Curso_has_Curso_Curso2_idx` (`CURSO_id_curso_prerequisito` ASC),
  INDEX `fk_Curso_has_Curso_Curso1_idx` (`CURSO_id_curso_requisito` ASC),
  CONSTRAINT `fk_Curso_has_Curso_Curso1`
    FOREIGN KEY (`CURSO_id_curso_requisito`)
    REFERENCES `mydb`.`curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Curso_has_Curso_Curso2`
    FOREIGN KEY (`CURSO_id_curso_prerequisito`)
    REFERENCES `mydb`.`curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
